// prisma/seed.js
// Run this script with `node prisma/seed.js`
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // Clear existing data
  await prisma.incidentReport.deleteMany();
  await prisma.user.deleteMany();

  // Create sample users
  await prisma.user.createMany({
    data: [
      {
        name: "Adam Dobmeier",
        email: "adam@convergehospitality.com",
        phone: "7013067524",
        username: "Adam",
        password: "1947",
        property: "Corporate Office",
        propertyAddress: "2244 County Road 12, Erie, CO 80516",
        propertyCode: "N/A",
        position: "CEO",
        active: true,
      },
      {
        name: "Steve Jensen",
        email: "steve@convergehospitality.com",
        phone: "3202675183",
        username: "Steve",
        password: "7283",
        property: "Corporate Office",
        propertyAddress: "2244 County Road 12, Erie, CO 80516",
        propertyCode: "N/A",
        position: "Executive Director of Operations",
        active: true,
      },
      {
        name: "Ambur Jensen",
        email: "ambur@convergehospitality.com",
        phone: "7195026835",
        username: "Ambur",
        password: "4651",
        property: "Corporate Office",
        propertyAddress: "2244 County Road 12, Erie, CO 80516",
        propertyCode: "N/A",
        position: "VP of Operational Excellence",
        active: true,
      },
      {
        name: "Will Southern",
        email: "will@convergehospitality.com",
        phone: "7012385494",
        username: "Will",
        password: "8029",
        property: "Corporate Office",
        propertyAddress: "2244 County Road 12, Erie, CO 80516",
        propertyCode: "N/A",
        position: "Regional Director of Operations",
        active: true,
      },
      {
        name: "Nick Nelson",
        email: "nick@convergehospitality.com",
        phone: "7016001138",
        username: "Nick",
        password: "3175",
        property: "Corporate Office",
        propertyAddress: "2244 County Road 12, Erie, CO 80516",
        propertyCode: "N/A",
        position: "Area Director of Operations",
        active: true,
      },
      {
        name: "Abby Clark",
        email: "abby@convergehospitality.com",
        phone: "3038017215",
        username: "Abby",
        password: "6492",
        property: "Corporate Office",
        propertyAddress: "2244 County Road 12, Erie, CO 80516",
        propertyCode: "N/A",
        position: "Human Resources Manager",
        active: true,
      },
      {
        name: "Taylor Neil",
        email: "taylor@convergehospitality.com",
        phone: "3039614789",
        username: "Taylor",
        password: "2508",
        property: "Corporate Office",
        propertyAddress: "2244 County Road 12, Erie, CO 80516",
        propertyCode: "N/A",
        position: "Corporate Task Force Manager",
        active: true,
      },
      {
        name: "Javier Cruz",
        email: "javier.cruz@convergehospitality.com",
        phone: "5209126192",
        username: "Javier",
        password: "9360",
        property: "la-posada-lodge-casitas-tucson-az",
        propertyAddress: "5900 N Oracle Rd, Tucson, AZ 85704",
        propertyCode: "az.389",
        position: "General Manager",
        active: true,
      },
      {
        name: "Maria Kustor",
        email: "maria.kustor@convergehospitality.com",
        phone: "5203120383",
        username: "Maria",
        password: "5814",
        property: "la-posada-lodge-casitas-tucson-az",
        propertyAddress: "5900 N Oracle Rd, Tucson, AZ 85704",
        propertyCode: "az.389",
        position: "Assistant General Manager",
        active: true,
      },
      {
        name: "Gilbert Gallardo",
        email: "gilbert.gallardo@convergehospitality.com",
        phone: "7029554492",
        username: "Gilbert",
        password: "0736",
        property: "fairfield-inn-suites-by-marriott-des-moines-ia",
        propertyAddress: "207 Crocker St, Des Moines, IA 50309",
        propertyCode: "DSMFD",
        position: "General Manager",
        active: true,
      },
      {
        name: "Jodi Doyle",
        email: "jodi.doyle@convergehospitality.com",
        phone: "5157770335",
        username: "Jodi",
        password: "4057",
        property: "fairfield-inn-suites-by-marriott-des-moines-ia",
        propertyAddress: "207 Crocker St, Des Moines, IA 50309",
        propertyCode: "DSMFD",
        position: "Assistant General Manager",
        active: true,
      },
      {
        name: "Cody Bingham",
        email: "cody.bingham@convergehospitality.com",
        phone: "5636130969",
        username: "Cody",
        password: "1269",
        property: "fairfield-inn-suites-by-marriott-norwalk-ia",
        propertyAddress: "2100 Hughes Dr, Norwalk, IA 50211",
        propertyCode: "DSMNF",
        position: "General Manager",
        active: true,
      },
      {
        name: "Glenda Wilaby",
        email: "glenda.wilaby@convergehospitality.com",
        phone: "5159546585",
        username: "Glenda",
        password: "7593",
        property: "fairfield-inn-suites-by-marriott-norwalk-ia",
        propertyAddress: "2100 Hughes Dr, Norwalk, IA 50211",
        propertyCode: "DSMNF",
        position: "Assistant General Manager",
        active: true,
      },
      {
        name: "Bhagat Rawat",
        email: "bhagat@fairfieldcrnorth.com",
        phone: "5635283411",
        username: "Bhagat",
        password: "8810",
        property: "fairfield-inn-suites-by-marriott-cedar-rapids-ia",
        propertyAddress: "605 32nd Ave SW, Cedar Rapids, IA 52404",
        propertyCode: "CIDFN",
        position: "General Manager / Owner",
        active: true,
      },
      {
        name: "Aaron Sprague",
        email: "aaron.sprague@convergehospitality.com",
        phone: "9132932783",
        username: "Aaron",
        password: "3324",
        property:
          "springhill-suites-by-marriott-kansas-city-airport-kansas-city-mo",
        propertyAddress: "8303 N Stoddard Ave, Kansas City, MO 64152",
        propertyCode: "MCINR",
        position: "General Manager",
        active: true,
      },
      {
        name: "Houston Hatfield",
        email: "houston.hatfield@convergehospitality.com",
        phone: "6208059713",
        username: "Houston",
        password: "6645",
        property:
          "springhill-suites-by-marriott-kansas-city-airport-kansas-city-mo",
        propertyAddress: "8303 N Stoddard Ave, Kansas City, MO 64152",
        propertyCode: "MCINR",
        position: "Assistant General Manager",
        active: true,
      },
      {
        name: "Amy Triepke",
        email: "amy.triepke@convergehospitality.com",
        phone: "N/A",
        username: "Amy",
        password: "2901",
        property: "woodsprings-suites-fargo-fargo-nd",
        propertyAddress: "1090 35th St N, Fargo, ND 58102",
        propertyCode: "ND.114",
        position: "General Manager",
        active: true,
      },
      {
        name: "David Johnston",
        email: "david.johnston@convergehospitality.com",
        phone: "2188410863",
        username: "David",
        password: "5478",
        property: "fairfield-inn-suites-by-marriott-detroit-lakes-mn",
        propertyAddress: "102 W Lake Dr, Detroit Lakes, MN 56501",
        propertyCode: "DTLFI",
        position: "General Manager",
        active: true,
      },
      {
        name: "Ellen Betzold",
        email: "ellen.betzold@convergehospitality.com",
        phone: "2183937259",
        username: "Ellen",
        password: "9132",
        property: "fairfield-inn-suites-by-marriott-duluth-mn",
        propertyAddress: "1510 Maple Grove Rd, Duluth, MN 55811",
        propertyCode: "DLFHW",
        position: "General Manager",
        active: true,
      },
      {
        name: "Shawna Crawford",
        email: "shawna.crawford@convergehospitality.com",
        phone: "7158170375",
        username: "Shawna",
        password: "0687",
        property: "fairfield-inn-suites-by-marriott-duluth-mn",
        propertyAddress: "1510 Maple Grove Rd, Duluth, MN 55811",
        propertyCode: "DLFHW",
        position: "Assistant General Manager",
        active: true,
      },
      {
        name: "Kassandra Jara",
        email: "kassandra.jara@convergehospitality.com",
        phone: "3085393932",
        username: "Kassandra",
        password: "4315",
        property: "fairfield-inn-suites-north-platte-ne",
        propertyAddress: "319 W South River Rd, North Platte, NE 69101",
        propertyCode: "LBFFI",
        position: "General Manager",
        active: true,
      },
      {
        name: "Yeni Fernandez",
        email: "yeni.fernandez@convergehospitality.com",
        phone: "7865801541",
        username: "Yeni",
        password: "1856",
        property: "hampton-inn-and-suites-omaha-la-vista-la-vista-ne",
        propertyAddress: "12331 Southport Pkwy, La Vista, NE 68128",
        propertyCode: "OMALV",
        position: "General Manager",
        active: true,
      },
      {
        name: "Cynthia Ortega",
        email: "cynthia.ortega@convergehospitality.com",
        phone: "5755134322",
        username: "Cynthia",
        password: "7109",
        property: "hampton-inn-suites-by-hilton-artesia-nm",
        propertyAddress: "2501 S Permian Pavilion Ave, Artesia, NM 88210",
        propertyCode: "OMALV",
        position: "General Manager",
        active: true,
      },
      {
        name: "Julissa Soto",
        email: "julissa.soto@convergehospitality.com",
        phone: "2104492279",
        username: "Julissa",
        password: "3582",
        property: "hampton-inn-suites-by-hilton-artesia-nm",
        propertyAddress: "2501 S Permian Pavilion Ave, Artesia, NM 88210",
        propertyCode: "OMALV",
        position: "OPS Manager",
        active: true,
      },
      {
        name: "Les Huber",
        email: "les.huber@convergehospitality.com",
        phone: "5757066102",
        username: "Les",
        password: "6094",
        property: "hampton-inn-suites-by-hilton-carlsbad-nm",
        propertyAddress: "120 Esperanza Cir, Carlsbad, NM 88220",
        propertyCode: "CNMNM",
        position: "General Manager",
        active: true,
      },
      {
        name: "Cheslie Onsurez",
        email: "cheslie.onsurez@convergehospitality.com",
        phone: "5758400499",
        username: "Cheslie",
        password: "2348",
        property: "hampton-inn-suites-by-hilton-carlsbad-nm",
        propertyAddress: "120 Esperanza Cir, Carlsbad, NM 88220",
        propertyCode: "CNMNM",
        position: "OPS Manager",
        active: true,
      },
      {
        name: "Andrea Deena Valesquez",
        email: "andrea.dv@convergehospitality.com",
        phone: "7142322020",
        username: "Andrea",
        password: "8713",
        property: "holiday-inn-express-suites-jenks-ok",
        propertyAddress: "150 Aquarium Dr, Jenks, OK 74037",
        propertyCode: "TULJS",
        position: "General Manager",
        active: true,
      },
      {
        name: "Margarita Pardo",
        email: "margarita.pardo@convergehospitality.com",
        phone: "5805604475",
        username: "Margarita",
        password: "5960",
        property: "holiday-inn-express-suites-jenks-ok",
        propertyAddress: "150 Aquarium Dr, Jenks, OK 74037",
        propertyCode: "TULJS",
        position: "OPS Manager",
        active: true,
      },
      {
        name: "Jasmine Hackett",
        email: "jasmine.hackett@convergehospitality.com",
        phone: "6829990620",
        username: "Jasmine",
        password: "0427",
        property:
          "fairfield-inn-suites-by-marriott-tulsa-south-medical-district-tulsa-ok",
        propertyAddress: "9150 S 102nd E Ave, Tulsa, OK 74133",
        propertyCode: "TULCR",
        position: "Assistant General Manager",
        active: true,
      },
      {
        name: "Vian Goff",
        email: "vian.goff@convergehospitality.com",
        phone: "5802314238",
        username: "Vian",
        password: "4871",
        property: "glo-best-western-enid-ok",
        propertyAddress: "123 W Maine St, Enid, OK 73701",
        propertyCode: "37140",
        position: "General Manager",
        active: true,
      },
      {
        name: "Merrie Willis",
        email: "merrie.willis@convergehospitality.com",
        phone: "4055581968",
        username: "Merrie",
        password: "1195",
        property: "residence-inn-norman-norman-ok",
        propertyAddress: "2400 Conference Dr, Norman, OK 73069",
        propertyCode: "OKCRN",
        position: "General Manager",
        active: true,
      },
      {
        name: "Katherine Griek",
        email: "katherine.griek@convergehospitality.com",
        phone: "7208992503",
        username: "Katherine",
        password: "7720",
        property: "residence-inn-norman-norman-ok",
        propertyAddress: "2400 Conference Dr, Norman, OK 73069",
        propertyCode: "OKCRN",
        position: "Assistant General Manager",
        active: true,
      },
      {
        name: "Ashley Back",
        email: "ashley.back@convergehospitality.com",
        phone: "N/A",
        username: "Ashley",
        password: "3056",
        property: "Hampton-inn-Suites-Tulsa-Central",
        propertyAddress: "3418 S. 79th East Avenue, Tulsa, OK 74145",
        propertyCode: "TULCE",
        position: "General Manager",
        active: true,
      },
      {
        name: "Toure Jimison",
        email: "toure.jimison@convergehospitality.com",
        phone: "3184701230",
        username: "Toure",
        password: "6203",
        property: "courtyard-sherman-sherman-tx",
        propertyAddress: "4344 N Loy Lake Rd, Sherman, TX 75092",
        propertyCode: "PNxCY",
        position: "General Manager",
        active: true,
      },
      {
        name: "Pamela Stanley",
        email: "pamela.stanley@convergehospitality.com",
        phone: "5807454265",
        username: "Pamela",
        password: "2539",
        property: "courtyard-sherman-sherman-tx",
        propertyAddress: "4344 N Loy Lake Rd, Sherman, TX 75092",
        propertyCode: "PNxCY",
        position: "Assistant General Manager",
        active: true,
      },
      {
        name: "Bridget Stanton",
        email: "bridget.stanton@convergehospitality.com",
        phone: "7204425876",
        username: "Bridget",
        password: "8984",
        property: "comfort-suites-by-choice",
        propertyAddress: "4777 Broadway, Boulder, CO 80304",
        propertyCode: "CO.439",
        position: "General Manager",
        active: true,
      },
      {
        name: "Isaiah Arriola",
        email: "isaiah.arriola@convergehospitality.com",
        phone: "7206414280",
        username: "Isaiah",
        password: "5340",
        property: "comfort-suites-by-choice",
        propertyAddress: "4777 Broadway , Boulder, CO 80304",
        propertyCode: "CO.439",
        position: "OPS Manager",
        active: true,
      },
      {
        name: "Samantha Fisher",
        email: "samantha.fisher@convergehospitality.com",
        phone: "7206180589",
        username: "Samantha",
        password: "0012",
        property: "boulder-university-inn-boulder-co",
        propertyAddress: "1632 Broadway, Boulder, CO 80302",
        propertyCode: "N/A",
        position: "General Manager",
        active: true,
      },
      {
        name: "Andrew Apadoca",
        email: "andrew.apadoca@convergehospitality.com",
        phone: "7208121250",
        username: "Andrew",
        password: "4467",
        property: "even-hotel-by-ihg-denver-tech-center-englewood-co",
        propertyAddress: "7380 S Clinton St, Englewood, CO 80112",
        propertyCode: "DENEW",
        position: "General Manager",
        active: true,
      },
      {
        name: "Ethan Coleman",
        email: "ethan.coleman@convergehospitality.com",
        phone: "N/A",
        username: "Ethan",
        password: "1793",
        property: "even-hotel-by-ihg-denver-tech-center-englewood-co",
        propertyAddress: "7380 S Clinton st, Englewood, CO 80112",
        propertyCode: "DENEW",
        position: "FOM",
        active: true,
      },
      {
        name: "Michelle Kelly",
        email: "michelle.kelly@convergehospitality.com",
        phone: "7203246018",
        username: "Michelle",
        password: "7035",
        property: "fairfield-inn-suites-by-marriott-aurora-co",
        propertyAddress: "13851 E Harvard Ave, Aurora, CO 80014",
        propertyCode: "DENAU",
        position: "General Manager",
        active: true,
      },
      {
        name: "Gabrielle McClain",
        email: "gabrielle.mcclain@convergehospitality.com",
        phone: "3036418014",
        username: "Gabrielle",
        password: "3681",
        property: "fairfield-inn-suites-by-marriott-aurora-co",
        propertyAddress: "13851 E Harvard Ave, Aurora, CO 80014",
        propertyCode: "DENAU",
        position: "Assistant General Manager",
        active: true,
      },
      {
        name: "Rachel Barrows",
        email: "rachel.barrows@convergehospitality.com",
        phone: "N/A",
        username: "Rachel",
        password: "6942",
        property:
          "fairfield-inn-suites-by-marriott-denver-airport-at-gateway-park",
        propertyAddress: "16191 E 40th Ave, Denver, CO 80239",
        propertyCode: "DENFY",
        position: "General Manager",
        active: true,
      },
      {
        name: "Kevin Rafter",
        email: "kevin.rafter@convergehospitality.com",
        phone: "8324832402",
        username: "Kevin",
        password: "2278",
        property: "holiday-inn-express-suites-firestone-co",
        propertyAddress: "11256 Business Park Cir, Firestone, CO 80504",
        propertyCode: "QWMFS",
        position: "General Manager",
        active: true,
      },
      {
        name: "Ashley Samuelson",
        email: "ashley.samuelson@convergehospitality.com",
        phone: "5054295048",
        username: "AshleyS",
        password: "8524",
        property: "holiday-inn-express-suites-firestone-co",
        propertyAddress: "11256 Business Park Cir, Firestone, CO 80504",
        propertyCode: "QWMFS",
        position: "Assistant General Manager",
        active: true,
      },
      {
        name: "Bradie Dodson",
        email: "bradie.dodson@convergehospitality.com",
        phone: "8064378657",
        username: "Bradie",
        password: "5079",
        property: "fairfield-inn-and-suites-fort-collins-fort-collins-co",
        propertyAddress: "3520 Timberwood Dr, Fort Collins, CO 80528",
        propertyCode: "FTCFF",
        position: "General Manager",
        active: true,
      },
      {
        name: "Cherie Schultz",
        email: "cherie.schultz@convergehospitality.com",
        phone: "9706328690",
        username: "Cherie",
        password: "0331",
        property: "fairfield-inn-and-suites-fort-collins-fort-collins-co",
        propertyAddress: "3520 Timberwood Dr, Fort Collins, CO 80528",
        propertyCode: "FTCFF",
        position: "Assistant General Manager",
        active: true,
      },
      {
        name: "Tara Lloyd",
        email: "tara.lloyd@convergehospitality.com",
        phone: "5054197104",
        username: "Tara",
        password: "4186",
        property: "loge-wolf-creek-south-fork-co",
        propertyAddress: "31042 US-160, South Fork, CO 81154",
        propertyCode: "N/A",
        position: "General Manager",
        active: true,
      },
      {
        name: "Kaitlyn Perez Cuevas",
        email: "kaitlyn.perez@convergehospitality.com",
        phone: "3034838114",
        username: "Kaitlyn",
        password: "1549",
        property: "fairfield-inn-and-suites-westminster-westminster-co",
        propertyAddress: "12080 N Melody Dr, Westminster, CO 80234",
        propertyCode: "DENWT",
        position: "Gerneral Manager",
        active: true,
      },
      {
        name: "Violet Mead",
        email: "violet.mead@convergehospitality.com",
        phone: "N/A",
        username: "Violet",
        password: "7802",
        property: "fairfield-inn-and-suites-westminster-westminster-co",
        propertyAddress: "12080 N Melody Dr, Westminster, CO 80234",
        propertyCode: "DENWT",
        position: "FOM",
        active: true,
      },
      {
        name: "Sarah Kitchenwitz",
        email: "sarah.kitchenwitz@convergehospitality.com",
        phone: "9703194493",
        username: "Sarah",
        password: "3916",
        property: "a-quinta-inn-suites-by-wyndham-rifle-co",
        propertyAddress: "600 Wapiti Ct, Rifle, CO 81650",
        propertyCode: "52686",
        position: "General Manager",
        active: true,
      },
      {
        name: "Kimberly Bair",
        email: "kimberly.bair@convergehospitality.com",
        phone: "N/A",
        username: "Kimberly",
        password: "6150",
        property: "a-quinta-inn-suites-by-wyndham-rifle-co",
        propertyAddress: "600 Wapiti Ct, Rifle, CO 81650",
        propertyCode: "52686",
        position: "Assistant General Manager",
        active: true,
      },
    ],
  });

  // Create sample incident reports
  await prisma.incidentReport.createMany({
    data: [
      {
        author: "Javier Cruz",
        authorEmail: "javier.cruz@convergehospitality.com",
        authorPhone: "5209126192",
        authorPosition: "General Manager",
        authorProperty: "la-posada-lodge-casitas-tucson-az",
        theft: true,
        propertyDamage: false,
        injury: false,
        declined: false,
        firstaid: false,
        medicalTreatment: false,
        emergencyTreatment: false,
        affectedName: "John Martinez",
        affectedAddress: "720 W Prince Rd, Tucson, AZ",
        affectedPhone: "5209981122",
        affectedEmail: "john.martinez@email.com",
        affiliation: "Guest",
        guest: true,
        employee: false,
        vendor: false,
        incidentTime: "21:15",
        incidentDate: "2025-09-14",
        emergencyServices: "Tucson Police",
        emergencyServicesCYes: true,
        emergencyServicesCNo: false,
        incidentDescription:
          "Guest reported theft of a backpack from his vehicle parked in the lot. Police were called and a report was filed.",
        otherName1: "",
        otherPhone1: "",
        otherName2: "",
        otherPhone2: "",
        otherName3: "",
        otherPhone3: "",
        witnessName1: "Maria Lopez",
        witnessPhone1: "5206627741",
        witnessName2: "",
        witnessPhone2: "",
        witnessName3: "",
        witnessPhone3: "",
        stolenItem: "Backpack with personal items",
        stolenItemValue: "$350",
        compensation: "Guest declined compensation.",
        compensationYes: false,
        compensationNo: true,
        weather: "Clear evening, 82°F",
        guestImpact: "Frustrated but cooperative",
        restorationCompany: "",
        photosYes: true,
        photosNo: false,
        physicianName: "",
        physicianAddress: "",
        DOB: "",
        shoes: "",
        training: "",
        daysOff: "",
        returnDate: "",
      },
      {
        author: "Maria Kustor",
        authorEmail: "maria.kustor@convergehospitality.com",
        authorPhone: "5203120383",
        authorPosition: "Assistant General Manager",
        authorProperty: "la-posada-lodge-casitas-tucson-az",
        theft: false,
        propertyDamage: true,
        injury: false,
        declined: false,
        firstaid: false,
        medicalTreatment: false,
        emergencyTreatment: false,
        affectedName: "Carlos Ramirez",
        affectedAddress: "Guest Room 208",
        affectedPhone: "",
        affectedEmail: "",
        affiliation: "Guest",
        guest: true,
        employee: false,
        vendor: false,
        incidentTime: "14:45",
        incidentDate: "2025-09-12",
        emergencyServices: "",
        emergencyServicesCYes: false,
        emergencyServicesCNo: true,
        incidentDescription:
          "Guest reported water damage from a leaking A/C unit causing carpet and personal shoes to be wet.",
        otherName1: "",
        otherPhone1: "",
        otherName2: "",
        otherPhone2: "",
        otherName3: "",
        otherPhone3: "",
        witnessName1: "Housekeeping Staff - Ana",
        witnessPhone1: "",
        witnessName2: "",
        witnessPhone2: "",
        witnessName3: "",
        witnessPhone3: "",
        stolenItem: "",
        stolenItemValue: "",
        compensation: "Provided complimentary cleaning service.",
        compensationYes: true,
        compensationNo: false,
        weather: "Sunny, 90°F",
        guestImpact: "Minor inconvenience, accepted resolution",
        restorationCompany: "Desert Dry Restoration",
        photosYes: true,
        photosNo: false,
        physicianName: "",
        physicianAddress: "",
        DOB: "",
        shoes: "Adidas sneakers",
        training: "",
        daysOff: "",
        returnDate: "",
      },
      {
        author: "Gilbert Gallardo",
        authorEmail: "gilbert.gallardo@convergehospitality.com",
        authorPhone: "7029554492",
        authorPosition: "General Manager",
        authorProperty: "fairfield-inn-suites-by-marriott-des-moines-ia",
        theft: true,
        propertyDamage: false,
        injury: false,
        declined: false,
        firstaid: false,
        medicalTreatment: false,
        emergencyTreatment: false,
        affectedName: "Emily Johnson",
        affectedAddress: "Des Moines, IA",
        affectedPhone: "5154401221",
        affectedEmail: "emily.johnson@email.com",
        affiliation: "Guest",
        guest: true,
        employee: false,
        vendor: false,
        incidentTime: "10:30",
        incidentDate: "2025-09-10",
        emergencyServices: "Local Police",
        emergencyServicesCYes: true,
        emergencyServicesCNo: false,
        incidentDescription:
          "Guest's purse was stolen from breakfast area when unattended. Police notified immediately.",
        otherName1: "",
        otherPhone1: "",
        otherName2: "",
        otherPhone2: "",
        otherName3: "",
        otherPhone3: "",
        witnessName1: "Front Desk Agent - Sarah",
        witnessPhone1: "",
        witnessName2: "",
        witnessPhone2: "",
        witnessName3: "",
        witnessPhone3: "",
        stolenItem: "Coach purse",
        stolenItemValue: "$500",
        compensation: "Guest declined compensation.",
        compensationYes: false,
        compensationNo: true,
        weather: "Clear morning, 75°F",
        guestImpact: "Upset, left early",
        restorationCompany: "",
        photosYes: false,
        photosNo: true,
        physicianName: "",
        physicianAddress: "",
        DOB: "",
        shoes: "",
        training: "",
        daysOff: "",
        returnDate: "",
      },
      {
        author: "Jodi Doyle",
        authorEmail: "jodi.doyle@convergehospitality.com",
        authorPhone: "5157770335",
        authorPosition: "Assistant General Manager",
        authorProperty: "fairfield-inn-suites-by-marriott-des-moines-ia",
        theft: false,
        propertyDamage: true,
        injury: false,
        declined: false,
        firstaid: false,
        medicalTreatment: false,
        emergencyTreatment: false,
        affectedName: "Hotel Property",
        affectedAddress: "Pool Area",
        affectedPhone: "",
        affectedEmail: "",
        affiliation: "",
        guest: false,
        employee: false,
        vendor: false,
        incidentTime: "17:20",
        incidentDate: "2025-09-09",
        emergencyServices: "",
        emergencyServicesCYes: false,
        emergencyServicesCNo: true,
        incidentDescription:
          "Guest broke a glass bottle in pool area, causing minor damage and requiring cleanup.",
        otherName1: "",
        otherPhone1: "",
        otherName2: "",
        otherPhone2: "",
        otherName3: "",
        otherPhone3: "",
        witnessName1: "Lifeguard - Tom",
        witnessPhone1: "",
        witnessName2: "",
        witnessPhone2: "",
        witnessName3: "",
        witnessPhone3: "",
        stolenItem: "",
        stolenItemValue: "",
        compensation: "N/A",
        compensationYes: false,
        compensationNo: true,
        weather: "Sunny, 88°F",
        guestImpact: "Pool closed for 1 hour",
        restorationCompany: "",
        photosYes: true,
        photosNo: false,
        physicianName: "",
        physicianAddress: "",
        DOB: "",
        shoes: "",
        training: "",
        daysOff: "",
        returnDate: "",
      },
      {
        author: "Cody Bingham",
        authorEmail: "cody.bingham@convergehospitality.com",
        authorPhone: "5636130969",
        authorPosition: "General Manager",
        authorProperty: "fairfield-inn-suites-by-marriott-norwalk-ia",
        theft: false,
        propertyDamage: false,
        injury: true,
        declined: false,
        firstaid: true,
        medicalTreatment: false,
        emergencyTreatment: false,
        affectedName: "David Wilson",
        affectedAddress: "Room 305",
        affectedPhone: "5159982211",
        affectedEmail: "",
        affiliation: "Guest",
        guest: true,
        employee: false,
        vendor: false,
        incidentTime: "19:00",
        incidentDate: "2025-09-08",
        emergencyServices: "",
        emergencyServicesCYes: false,
        emergencyServicesCNo: true,
        incidentDescription:
          "Guest slipped on wet floor near ice machine. First aid provided for minor scrape on elbow.",
        otherName1: "",
        otherPhone1: "",
        otherName2: "",
        otherPhone2: "",
        otherName3: "",
        otherPhone3: "",
        witnessName1: "Housekeeping - Jane",
        witnessPhone1: "",
        witnessName2: "",
        witnessPhone2: "",
        witnessName3: "",
        witnessPhone3: "",
        stolenItem: "",
        stolenItemValue: "",
        compensation: "Provided complimentary room service.",
        compensationYes: true,
        compensationNo: false,
        weather: "Rain earlier, floor wet from guests",
        guestImpact: "Minor injury, stayed overnight",
        restorationCompany: "",
        photosYes: true,
        photosNo: false,
        physicianName: "",
        physicianAddress: "",
        DOB: "1984-07-12",
        shoes: "Sandals",
        training: "",
        daysOff: "",
        returnDate: "",
      },
      {
        author: "Lisa Edwards",
        authorEmail: "lisa.edwards@convergehospitality.com",
        authorPhone: "4027712345",
        authorPosition: "Assistant General Manager",
        authorProperty: "fairfield-inn-omaha-ne",
        theft: false,
        propertyDamage: false,
        injury: true,
        declined: false,
        firstaid: false,
        medicalTreatment: true,
        emergencyTreatment: false,
        affectedName: "Michael Stevens",
        affectedAddress: "Lobby",
        affectedPhone: "4025547788",
        affectedEmail: "michael.stevens@email.com",
        affiliation: "Vendor",
        guest: false,
        employee: false,
        vendor: true,
        incidentTime: "08:15",
        incidentDate: "2025-09-06",
        emergencyServices: "",
        emergencyServicesCYes: false,
        emergencyServicesCNo: true,
        incidentDescription:
          "Vendor tripped over lobby rug while delivering supplies. Taken to urgent care for ankle sprain.",
        otherName1: "",
        otherPhone1: "",
        otherName2: "",
        otherPhone2: "",
        otherName3: "",
        otherPhone3: "",
        witnessName1: "Front Desk Clerk - Josh",
        witnessPhone1: "",
        witnessName2: "",
        witnessPhone2: "",
        witnessName3: "",
        witnessPhone3: "",
        stolenItem: "",
        stolenItemValue: "",
        compensation: "N/A",
        compensationYes: false,
        compensationNo: true,
        weather: "Cloudy, 70°F",
        guestImpact: "Minimal, lobby cleared quickly",
        restorationCompany: "",
        photosYes: true,
        photosNo: false,
        physicianName: "Dr. Patel",
        physicianAddress: "Omaha Urgent Care",
        DOB: "1979-03-22",
        shoes: "Work boots",
        training: "",
        daysOff: "2 days recommended",
        returnDate: "2025-09-08",
      },
      {
        author: "Kevin Harris",
        authorEmail: "kevin.harris@convergehospitality.com",
        authorPhone: "3194489987",
        authorPosition: "General Manager",
        authorProperty: "fairfield-inn-cedar-rapids-ia",
        theft: false,
        propertyDamage: true,
        injury: false,
        declined: false,
        firstaid: false,
        medicalTreatment: false,
        emergencyTreatment: false,
        affectedName: "Hotel Property",
        affectedAddress: "Parking Lot",
        affectedPhone: "",
        affectedEmail: "",
        affiliation: "",
        guest: false,
        employee: false,
        vendor: false,
        incidentTime: "23:45",
        incidentDate: "2025-09-05",
        emergencyServices: "Cedar Rapids Police",
        emergencyServicesCYes: true,
        emergencyServicesCNo: false,
        incidentDescription:
          "Unknown individual damaged light post in parking lot. Police notified.",
        otherName1: "",
        otherPhone1: "",
        otherName2: "",
        otherPhone2: "",
        otherName3: "",
        otherPhone3: "",
        witnessName1: "Night Auditor - Sam",
        witnessPhone1: "",
        witnessName2: "",
        witnessPhone2: "",
        witnessName3: "",
        witnessPhone3: "",
        stolenItem: "",
        stolenItemValue: "",
        compensation: "N/A",
        compensationYes: false,
        compensationNo: true,
        weather: "Clear, 65°F",
        guestImpact: "Minimal",
        restorationCompany: "Midwest Electric Repair",
        photosYes: true,
        photosNo: false,
        physicianName: "",
        physicianAddress: "",
        DOB: "",
        shoes: "",
        training: "",
        daysOff: "",
        returnDate: "",
      },
      {
        author: "Rachel Green",
        authorEmail: "rachel.green@convergehospitality.com",
        authorPhone: "5153342211",
        authorPosition: "Assistant General Manager",
        authorProperty: "springhill-suites-ames-ia",
        theft: true,
        propertyDamage: false,
        injury: false,
        declined: false,
        firstaid: false,
        medicalTreatment: false,
        emergencyTreatment: false,
        affectedName: "Sophia Lee",
        affectedAddress: "Guest Room 410",
        affectedPhone: "5157778899",
        affectedEmail: "sophia.lee@email.com",
        affiliation: "Guest",
        guest: true,
        employee: false,
        vendor: false,
        incidentTime: "16:10",
        incidentDate: "2025-09-03",
        emergencyServices: "Local Police",
        emergencyServicesCYes: true,
        emergencyServicesCNo: false,
        incidentDescription:
          "Guest reported jewelry missing from room. Police called for investigation.",
        otherName1: "",
        otherPhone1: "",
        otherName2: "",
        otherPhone2: "",
        otherName3: "",
        otherPhone3: "",
        witnessName1: "Housekeeper - Luis",
        witnessPhone1: "",
        witnessName2: "",
        witnessPhone2: "",
        witnessName3: "",
        witnessPhone3: "",
        stolenItem: "Gold necklace",
        stolenItemValue: "$1,200",
        compensation: "Guest declined, pending police case.",
        compensationYes: false,
        compensationNo: true,
        weather: "Sunny, 78°F",
        guestImpact: "Very upset, requested early checkout",
        restorationCompany: "",
        photosYes: false,
        photosNo: true,
        physicianName: "",
        physicianAddress: "",
        DOB: "",
        shoes: "",
        training: "",
        daysOff: "",
        returnDate: "",
      },
      {
        author: "Derrick White",
        authorEmail: "derrick.white@convergehospitality.com",
        authorPhone: "5631125544",
        authorPosition: "General Manager",
        authorProperty: "residence-inn-davenport-ia",
        theft: false,
        propertyDamage: false,
        injury: true,
        declined: false,
        firstaid: false,
        medicalTreatment: false,
        emergencyTreatment: true,
        affectedName: "Karen Mitchell",
        affectedAddress: "Lobby",
        affectedPhone: "5634412200",
        affectedEmail: "karen.mitchell@email.com",
        affiliation: "Employee",
        guest: false,
        employee: true,
        vendor: false,
        incidentTime: "12:50",
        incidentDate: "2025-09-02",
        emergencyServices: "EMS",
        emergencyServicesCYes: true,
        emergencyServicesCNo: false,
        incidentDescription:
          "Front desk employee experienced severe allergic reaction. EMS provided emergency treatment.",
        otherName1: "",
        otherPhone1: "",
        otherName2: "",
        otherPhone2: "",
        otherName3: "",
        otherPhone3: "",
        witnessName1: "Manager - Derrick",
        witnessPhone1: "",
        witnessName2: "",
        witnessPhone2: "",
        witnessName3: "",
        witnessPhone3: "",
        stolenItem: "",
        stolenItemValue: "",
        compensation: "N/A",
        compensationYes: false,
        compensationNo: true,
        weather: "Clear, 72°F",
        guestImpact: "None",
        restorationCompany: "",
        photosYes: false,
        photosNo: true,
        physicianName: "Dr. Lee",
        physicianAddress: "Davenport Medical Center",
        DOB: "1990-11-02",
        shoes: "Flats",
        training: "CPR-certified",
        daysOff: "3",
        returnDate: "2025-09-05",
      },
      {
        author: "Angela Brooks",
        authorEmail: "angela.brooks@convergehospitality.com",
        authorPhone: "5154412201",
        authorPosition: "Assistant General Manager",
        authorProperty: "towneplace-suites-ankeny-ia",
        theft: false,
        propertyDamage: true,
        injury: false,
        declined: false,
        firstaid: false,
        medicalTreatment: false,
        emergencyTreatment: false,
        affectedName: "Hotel Property",
        affectedAddress: "Laundry Room",
        affectedPhone: "",
        affectedEmail: "",
        affiliation: "",
        guest: false,
        employee: false,
        vendor: false,
        incidentTime: "05:20",
        incidentDate: "2025-09-01",
        emergencyServices: "Fire Department",
        emergencyServicesCYes: true,
        emergencyServicesCNo: false,
        incidentDescription:
          "Small fire in laundry dryer due to lint buildup. Fire department extinguished quickly. No injuries.",
        otherName1: "",
        otherPhone1: "",
        otherName2: "",
        otherPhone2: "",
        otherName3: "",
        otherPhone3: "",
        witnessName1: "Maintenance - Steve",
        witnessPhone1: "",
        witnessName2: "",
        witnessPhone2: "",
        witnessName3: "",
        witnessPhone3: "",
        stolenItem: "",
        stolenItemValue: "",
        compensation: "N/A",
        compensationYes: false,
        compensationNo: true,
        weather: "Clear night, 64°F",
        guestImpact: "Minimal, area restricted temporarily",
        restorationCompany: "Ankeny Fire Restoration",
        photosYes: true,
        photosNo: false,
        physicianName: "",
        physicianAddress: "",
        DOB: "",
        shoes: "",
        training: "Fire safety training scheduled",
        daysOff: "",
        returnDate: "",
      },
    ],
  });
}

main()
  .then(async () => {
    console.log("Seeding completed.");
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
